name: Build

# Trigger on push events and pull requests to the repository
on:
  push:
  pull_request:

jobs:
  build-linux:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:  
      - name: Checkout the code
        uses: actions/checkout@v3
  
      - name: Give execute permissions to the script
        run: chmod +x ./build_mac_linux.sh        

      - name: Build Linux version
        run: ./build_mac_linux.sh

      - name: Create the dist/linux folder
        run: mkdir -p ./dist/linux

      - name: Copy the Linux binary to the dist/linux folder
        run: cp usm ./dist/linux/

  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
  
      - name: Give execute permissions to the script
        run: chmod +x ./build_mac_linux.sh        

      - name: Build macOS version
        run: ./build_mac_linux.sh

      - name: Create the dist/macos folder
        run: mkdir -p ./dist/macos
      
      - name: Copy the macOS binary to the dist/macos folder
        run: cp usm ./dist/macos/
